### ISSUE TITLE
Use this for creating membership/payments/course

### ISSUE THREAD

**Issue by pooriaarab** [VanDerLars/notion_website_converter#1]
Hi, 

Superb job with this repo and doing this probably the simplest and easiest way possible. Thank you for that. 

I was wondering how 

a) Can we add payment gateway (e.g. pay to access the notion doc)? For an online course
b) Can we deploy this to Hostinger?

**Comment by VanDerLars** [comment]
Hey, thank you for appreciating this work.

a) I personally wouldn't do that here in notion2web:
- there are already working instances of this all over the world, I would have to provide a bunch of different payment gateways, cause every region of the world uses different ones.
- I would have to maintain them also in the future.
- It blows this project enormously for only a small use case.
- It is not really the purpose of this project. I wanted to bring an easy way to host the notion content separately from the notion instance itself.

My tipp: you an use a [password secured folder](https://stackoverflow.com/questions/5229656/password-protecting-a-directory-and-all-of-its-subfolders-using-htaccess). I also plan to implement something similar directly into notion2web.
You then have to setup the purchase process yourself in another website, and after the purchase went through, you provide the password to your notion2web page to you customers.

b) I never worked with a service of hostinger, but as long as they provide a simple webspace with php 8, then this will work. I personally would recommend to use the dockerfile to run notion2web, but this depends on your personal experience (its far more sophisticated than simply dragging and dropping files and folder onto a webspace).

Let me know if you have other questions or if I can assist you.

You can also suggest more features here.

Lars

**Comment by pooriaarab** [comment]
Hi Lars, 

Thanks for getting back to me so quick. 

The password secured folder approach seems a little bit tricky because anyone who has the password, could virtually use it, correct?

I've been scavenging the web for any way to setup my course on Notion but tools are either not working or there's no OSS way to do it. 

Similar models:
https://courses.so/
https://github.com/transitive-bullshit/nextjs-notion-starter-kit
https://www.youtube.com/watch?v=Bae5lqX4K9k

Based on what I know, guessing the NextJS-Notion starter kit is the best bet but connecting the payment gateway and user auth/membership is what's not present. Or another OSS version like float.so or courses.so. Apparently, the creator of Fruition said it takes a weekend to setup the whole thing.  


Using Notion2Web, I'm guessing there's no syncing correct? It'll just be a one-time export Notion 2 website and any changes will not be reflected? I might be wrong.

**Comment by VanDerLars** [comment]
Hey,
true, the folder workaround don't allow personal user accounts. But accounts also don't prevent account and password sharing though.

Setting up payment in n2web is as easy or hard as in any other software, programming language or tool. But, as I said, I personally won't develop such a function yet.

Therefore you could either fork n2web or make a pull request if you develop such functions by yourself. In the end, it is up to you, which way you go.

And yes, n2web uses the HTML-Export of Notion. It doesn't use the API (which is do by choice). This brings some advantages (speed, SEO, customization) but also downsides (no synch). If you need automatically syncing, then Friution could be the way, or you use the export tools here on Github which I use. 🙂
